
//BurgerBuilder.js
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_ING_FAILED = 'FETCH_ING_FAILED'


//Order.js
export const 	PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL'
export const PURCHASE_INIT = 'PURCHASE_INIT'

//Orders page

export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL'
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START'
